# This file should not be checked into git.
# This file is used to set environment variables that are not visible
# in version control.
# Environment variables set here overwrite variables of the same name
# set in config.toml

[env]
JWT_SECRET = "..."

